version: "3.9"
services:
  pybox:
    build:
      context: .
      dockerfile: Py.dockerfile
    tty: true
  rbox:
    build:
      context: .
      dockerfile: R.dockerfile
    tty: true
  server:
    build:
      context: .
      dockerfile: server.dockerfile
    tty: true
