name: BioDock

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build Python Docker image
      run: docker build -f Py.dockerfile -t py:${{ github.sha }}
    - name: Build R Docker image
      run: docker build -f R.dockerfile -t r:${{ github.sha }}
    - name: Build minimal GNU/Linux Docker image
      run: docker build -f sh.dockerfile -t sh:${{ github.sha }}
    - name: Build bioinformatics dev Docker image
      run: docker build -f bsh.dockerfile -t py:${{ github.sha }}
