name: BioDock

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Python Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Py.dockerfile
        tags: py:${{ github.sha }}
        push: false
    
    - name: Build R Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: R.dockerfile
        tags: r:${{ github.sha }}
        push: false
    
    - name: Build minimal Linux Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: sh.dockerfile
        tags: sh:${{ github.sha }}
        push: false
    
    - name: Build bioinformatics dev Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: bsh.dockerfile
        tags: bsh:${{ github.sha }}
        push: false
